(ns re-native.fcm
  (:require [reagent.core :as r]
            [re-frame.core :as re]))

(def react-native-fcm (js/require "react-native-fcm"))
(def FCM (aget react-native-fcm "default"))
(def FCMEvent (aget react-native-fcm "FCMEvent"))
(def FCMEventRefreshToken (aget FCMEvent "RefreshToken"))
(def FCMEventNotification (aget FCMEvent "Notification"))
(def RemoteNotificationResult (aget react-native-fcm "RemoteNotificationResult"))
(def RemoteNotificationResultNewData  (aget RemoteNotificationResult "NewData"))
(def RemoteNotificationResultNoData (aget RemoteNotificationResult "NoData"))
(def RemoteNotificationResultResultFailed (aget RemoteNotificationResult "ResultFailed"))
(def WillPresentNotificationResult (aget react-native-fcm "WillPresentNotificationResult"))
(def WillPresentNotificationResultAll (aget WillPresentNotificationResult "All"))
(def WillPresentNotificationResultNone (aget WillPresentNotificationResult "None"))
(def NotificationType (aget react-native-fcm "NotificationType"))
(def NotificationTypeRemote  (aget NotificationType "Remote"))
(def NotificationTypeNotificationResponse (aget NotificationType "NotificationResponse"))
(def NotificationTypeWillPresent (aget NotificationType "WillPresent"))
(def NotificationTypeLocal (aget NotificationType "Local"))

(assert react-native-fcm)
(assert FCM)
(assert FCMEvent)
(assert FCMEventRefreshToken)
(assert FCMEventNotification)
(assert RemoteNotificationResult)
(assert RemoteNotificationResultNewData)
(assert RemoteNotificationResultNoData)
(assert RemoteNotificationResultResultFailed)
(assert WillPresentNotificationResult)
(assert WillPresentNotificationResultAll)
(assert WillPresentNotificationResultNone)
(assert NotificationType)
(assert NotificationTypeRemote)
(assert NotificationTypeNotificationResponse)
(assert NotificationTypeWillPresent)
(assert NotificationTypeLocal)
